<?php
return [
    ['nama' => 'Umum', 'icon' => 'fas fa-bullhorn'],
    ['nama' => 'Politik', 'icon' => 'fas fa-landmark'],
    ['nama' => 'Ekonomi', 'icon' => 'fas fa-coins'],
    ['nama' => 'Olahraga', 'icon' => 'fas fa-futbol'],
    ['nama' => 'Teknologi', 'icon' => 'fas fa-microchip'],
    ['nama' => 'Pendidikan', 'icon' => 'fas fa-graduation-cap'],
    ['nama' => 'Kesehatan', 'icon' => 'fas fa-heartbeat'],
    ['nama' => 'Pembangunan', 'icon' => 'fas fa-tools'],
    ['nama' => 'Pertanian', 'icon' => 'fas fa-tractor'],
    ['nama' => 'Perikanan', 'icon' => 'fas fa-fish'],
    ['nama' => 'Lingkungan', 'icon' => 'fas fa-leaf'],
    ['nama' => 'Pariwisata', 'icon' => 'fas fa-umbrella-beach'],
    ['nama' => 'Transportasi', 'icon' => 'fas fa-bus'],
    ['nama' => 'Hiburan', 'icon' => 'fas fa-film'],
    ['nama' => 'Budaya', 'icon' => 'fas fa-theater-masks'],
    ['nama' => 'Musik', 'icon' => 'fas fa-music'],
    ['nama' => 'Film', 'icon' => 'fas fa-video'],
    ['nama' => 'Agama', 'icon' => 'fas fa-mosque'],
    ['nama' => 'Opini', 'icon' => 'fas fa-pen-nib'],
    ['nama' => 'Sosial', 'icon' => 'fas fa-users'],
    ['nama' => 'Startup', 'icon' => 'fas fa-lightbulb'],
    ['nama' => 'UMKM', 'icon' => 'fas fa-store'],
];
